# Generated by Django 3.2.7 on 2021-12-22 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Passive', 'passive')], default='passive', max_length=7)),
                ('cost_per_delivery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
