# Generated by Django 3.2.7 on 2021-12-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_management', '0004_rename_parent_category_id_category_parent_category_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category_guid',
        ),
    ]
