# Generated by Django 3.2.7 on 2021-12-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_management', '0005_remove_category_parent_category_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category_guid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
