# Generated by Django 3.2.7 on 2021-11-11 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Vehicle_Details',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_brand', models.CharField(blank=True, max_length=70, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=70, null=True)),
                ('vehicle_Type', models.CharField(blank=True, max_length=70, null=True)),
                ('year', models.IntegerField()),
                ('number_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_chesis_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_brand', models.CharField(blank=True, max_length=70, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=70, null=True)),
                ('vehicle_Type', models.CharField(blank=True, max_length=70, null=True)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
