# Generated by Django 3.2.7 on 2021-11-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_vehicle_details',
            name='service_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
