# Generated by Django 3.2.7 on 2021-11-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_customer_vehicle_details_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_vehicle_details',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
