# Generated by Django 3.2.7 on 2021-11-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0004_remove_customer_vehicle_details_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_vehicle_details',
            name='engine_chesis_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer_vehicle_details',
            name='number_plate',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
