# Generated by Django 3.2.7 on 2021-11-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
