# Generated by Django 3.2.7 on 2021-11-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0002_alter_services_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
