# Generated by Django 3.2.7 on 2021-11-18 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_customer_vehicle_details_service_price'),
        ('services_management', '0004_alter_services_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Provider_Services',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fixed_price', models.BooleanField()),
                ('rule_based', models.BooleanField()),
                ('relevant_technicians', models.CharField(blank=True, max_length=100, null=True)),
                ('service_on_site', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.customer_vehicle_details')),
            ],
        ),
    ]
