# Generated by Django 3.2.7 on 2021-11-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0005_service_provider_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider_services',
            name='fixed_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service_provider_services',
            name='rule_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service_provider_services',
            name='service_on_site',
            field=models.BooleanField(default=False),
        ),
    ]
