# Generated by Django 3.2.7 on 2021-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0007_auto_20211119_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_provider_services',
            name='service_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
