# Generated by Django 3.2.7 on 2022-01-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_provider_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
